export const options_language = [
    { value: '1', label: 'English' },
    { value: '2', label: 'Arabic' },
    { value: '3', label: 'Bengali' },
    { value: '4', label: 'French' },
    { value: '5', label: 'German' },
    { value: '6', label: 'Hindi' },
    { value: '7', label: 'Indonesian' },
    { value: '8', label: 'Italian' },
    { value: '9', label: 'Japanese' },
    { value: '10', label: 'Korean' },
    { value: '11', label: 'Malay' },
    { value: '12', label: 'Mandarin' },
    { value: '13', label: 'Polish' },
    { value: '14', label: 'Portugese' },
    { value: '15', label: 'Russian' },
    { value: '16', label: 'Spanish' },
    { value: '17', label: 'Turkish' },
    { value: '18', label: 'Vietnamese' },
];

export const options_major = [
    { value: '1', label: 'Aeronautics and Astronautics' },
    { value: '2', label: 'African and African American Studies' },
    { value: '3', label: 'American Studies' },
    { value: '4', label: 'Anthropology' },
    { value: '5', label: 'Archaeology' },
    { value: '6', label: 'Architectual Design' },
    { value: '7', label: 'Art History' },
    { value: '8', label: 'Art Practice' },
    { value: '9', label: 'Asian American Studies' },
    { value: '10', label: 'Atmosphere/ Enery' },
    { value: '11', label: 'Bioengineering' },
    { value: '12', label: 'Biology' },
    { value: '13', label: 'Biochemical Engineering' },
    { value: '14', label: 'Biomedical Computation' },
    { value: '15', label: 'Chemical Engineering' },
    { value: '16', label: 'Chemistry' },
    { value: '17', label: 'Civil and Environmental Engineering' },
    { value: '18', label: 'Classics' },
    { value: '19', label: 'Communication' },
    { value: '20', label: 'Comparative Literature' },
    { value: '21', label: 'Comparative Studies in Race and Ethnicity' },
    { value: '22', label: 'Computer Science' },
    { value: '23', label: 'Earth Systems' },
    { value: '24', label: 'East Asian Studies' },
    { value: '25', label: 'Economics' },
    { value: '26', label: 'Electrical Engineering' },
    { value: '27', label: 'Engineering Physics' },
    { value: '28', label: 'English' },
    { value: '29', label: 'Environmental Systems Engineering' },
    { value: '30', label: 'Feminist, Gender, and Sexuality Studies' },
    { value: '31', label: 'Film and Media Studies' },
    { value: '32', label: 'Geological Sciences' },
    { value: '33', label: 'Geophysics' },
    { value: '34', label: 'History' },
    { value: '35', label: 'Human Biology' },
    { value: '36', label: 'International Relations' },
    { value: '37', label: 'Linguistics' },
    { value: '38', label: 'Management Science and Engineering' },
    { value: '39', label: 'Material Science and Engineering' },
    { value: '40', label: 'Mathematical and Computational Science' },
    { value: '41', label: 'Mathematics' },
    { value: '42', label: 'Mechanical Engineering' },
    { value: '43', label: 'Philosophy' },
    { value: '44', label: 'Physics' },
    { value: '45', label: 'Political Science' },
    { value: '46', label: 'Product Design' },
    { value: '47', label: 'Psychology' },
    { value: '48', label: 'Public Policy' },
    { value: '49', label: 'Sociology' },
    { value: '50', label: 'Symbolic Systems' },
    { value: '51', label: 'Urban Studies' },
];

export const options_time = [
    { value: 5, label: '05:00' },
    { value: 6, label: '06:00' },
    { value: 7, label: '07:00' },
    { value: 8, label: '08:00' },
    { value: 9, label: '09:00' },
    { value: 10, label: '10:00' },
    { value: 11, label: '11:00' },
    { value: 12, label: '12:00' },
    { value: 13, label: '13:00' },
    { value: 14, label: '14:00' },
    { value: 15, label: '15:00' },
    { value: 16, label: '16:00' },
    { value: 17, label: '17:00' }
];

export const options_duration = [
    { value: 1, label: '1 hour' },
    { value: 2, label: '2 hour' },
    { value: 3, label: '3 hour' },
    { value: 4, label: '4 hour' },
    { value: 5, label: '5 hour' }
];

export const options_size = [
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
    { value: '6', label: '6' }
];